spring:
  application:
    name: rabbit-template
  datasource:
    url: jdbc:h2:mem:rabbitdb
    username: sa
    password:
  h2:
    console:
      enabled: true
      path: /h2-console
  jpa:
    hibernate:
      ddl-auto: create-drop
    show-sql: false
    properties:
      hibernate:
        format_sql: false
    database-platform: org.hibernate.dialect.H2Dialect
  rabbitmq:
    host: localhost
    port: 5672
    username: admin
    password: admin123
    virtual-host: /
    connection-timeout: 10000  #timeout para conectar ao RabbitMQ (10s)
    requested-heartbeat: 30  #heartbeat para manter conexão viva (30s)
    cache:
      channel:
        size: 10  #tamanho do pool de canais
      connection:
        size: 10  #tamanho do pool de conexões
    listener:
      simple:
        acknowledge-mode: auto
        retry:
          enabled: true  #ativa o retry
          max-attempts: 3  #tenta 3x
          initial-interval: 1000  #primeira tentativa aguarda 1s
          multiplier: 2.0  #cada tentativa dobra o tempo
          max-interval: 10000  #tempo maximo de espera é 10s

logging:
  level:
    org.hibernate.SQL: OFF
    org.hibernate.type.descriptor.sql.BasicBinder: OFF